### ISSUE TITLE
Continue.. please?

### ISSUE THREAD

**Issue by nelix** [vsmode/pixels#1]
Saw the start of this on codesandbox, was looking really interesting. Plus you have an interesting code composition style.

**Comment by jozanza** [comment]
Thanks for the compliments. I've been hacking on this project a lot locally. I'll push those commits next time I get some wifi :)

**Comment by jozanza** [comment]
@nelix codesandbox does not seem to want to import this repo (throws a 422 each time I try), so I deployed the current build to https://vsmode.github.io/pixels/. Cheers! 🥂

**Comment by nelix** [comment]
yay!
